import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Button } from "@/components/ui/button";
import { useState } from "react";

interface TermsAndConditionsProps {
  trigger: React.ReactNode;
  type: "terms" | "privacy";
}

export const TermsAndConditions = ({ trigger, type }: TermsAndConditionsProps) => {
  const [open, setOpen] = useState(false);

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>{trigger}</DialogTrigger>
      <DialogContent className="max-w-2xl max-h-[85vh] p-0">
        <DialogHeader className="px-6 pt-6 pb-2">
          <DialogTitle className="text-xl font-bold">
            {type === "terms" ? "Terms of Service" : "Privacy Policy"}
          </DialogTitle>
        </DialogHeader>
        <ScrollArea className="px-6 pb-6 max-h-[65vh]">
          {type === "terms" ? <TermsContent /> : <PrivacyContent />}
          <div className="flex justify-end mt-6 pb-2">
            <Button variant="outline" onClick={() => setOpen(false)}>
              Close
            </Button>
          </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
};

// ─── Terms of Service Content ───
const TermsContent = () => (
  <div className="prose prose-sm dark:prose-invert max-w-none space-y-4 text-sm text-muted-foreground leading-relaxed">
    <p className="text-xs text-muted-foreground/70 italic">Last Updated: March 2026</p>

    <p>
      Welcome to <strong className="text-foreground">Neesh AI</strong> ("the Platform"), an idea validation and AI-powered
      market research platform. By creating an account or using our services, you agree to be bound by these Terms of
      Service ("Terms"). Please read them carefully.
    </p>

    <h3 className="text-base font-semibold text-foreground mt-6">1. Acceptance of Terms</h3>
    <p>
      By accessing or using Neesh AI, you confirm that you are at least 18 years old (or the age of majority in your
      jurisdiction) and that you accept and agree to be bound by these Terms. If you do not agree, you may not use the
      Platform.
    </p>

    <h3 className="text-base font-semibold text-foreground mt-6">2. Description of Service</h3>
    <p>
      Neesh AI provides AI-powered tools for entrepreneurs and businesses to validate their ideas through market
      research, audience analysis, feedback collection, AI chatbots, and content generation. Our services include but
      are not limited to:
    </p>
    <ul className="list-disc pl-5 space-y-1">
      <li>Project creation and idea validation workflows</li>
      <li>AI-generated blog posts and content</li>
      <li>Audience persona generation and analysis</li>
      <li>Customizable feedback forms and surveys</li>
      <li>AI-powered chatbots for product research</li>
      <li>Knowledge base document uploads and RAG-based Q&A</li>
    </ul>

    <h3 className="text-base font-semibold text-foreground mt-6">3. User Accounts</h3>
    <p>
      You are responsible for maintaining the confidentiality of your account credentials. You agree to provide
      accurate, current, and complete information during registration and to update such information as necessary.
      You are solely responsible for all activities that occur under your account.
    </p>

    <h3 className="text-base font-semibold text-foreground mt-6">4. User Content & Intellectual Property</h3>
    <p>
      You retain ownership of all content, ideas, and data ("User Content") you submit to the Platform. By using
      Neesh AI, you grant us a limited, non-exclusive license to process your User Content solely for the purpose of
      providing our services to you. We do not claim ownership of your ideas or generated outputs.
    </p>
    <p>
      AI-generated content (blog posts, personas, analyses) is provided as a tool to assist your decision-making.
      You are free to use this output commercially, but you acknowledge it is generated by AI and should be reviewed
      for accuracy.
    </p>

    <h3 className="text-base font-semibold text-foreground mt-6">5. Acceptable Use</h3>
    <p>You agree not to:</p>
    <ul className="list-disc pl-5 space-y-1">
      <li>Use the Platform for any unlawful, harmful, or fraudulent purpose</li>
      <li>Attempt to reverse-engineer, decompile, or disassemble any part of the Platform</li>
      <li>Upload malicious content, viruses, or harmful code</li>
      <li>Interfere with the security or integrity of the Platform</li>
      <li>Use automated scripts or bots to access the Platform without prior written consent</li>
      <li>Resell, redistribute, or sublicense access to the Platform</li>
    </ul>

    <h3 className="text-base font-semibold text-foreground mt-6">6. Subscriptions & Payments</h3>
    <p>
      Certain features of Neesh AI may require a paid subscription. Pricing, billing cycles, and feature access are
      described on our pricing page. All payments are non-refundable unless otherwise stated. We reserve the right to
      change pricing with 30 days' prior notice.
    </p>

    <h3 className="text-base font-semibold text-foreground mt-6">7. API Keys & Third-Party Services</h3>
    <p>
      You may provide your own API keys for third-party AI providers (OpenAI, Claude, Gemini, etc.). You are solely
      responsible for the security and billing of these API keys. Neesh AI encrypts stored API keys but assumes no
      liability for charges incurred through third-party services.
    </p>

    <h3 className="text-base font-semibold text-foreground mt-6">8. Limitation of Liability</h3>
    <p>
      Neesh AI is provided "as is" and "as available." We make no warranties, express or implied, regarding the
      accuracy, reliability, or completeness of AI-generated content. To the maximum extent permitted by law, Neesh AI
      shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your
      use of the Platform.
    </p>

    <h3 className="text-base font-semibold text-foreground mt-6">9. Termination</h3>
    <p>
      We may suspend or terminate your account at any time for violation of these Terms. You may delete your account
      at any time. Upon termination, your right to use the Platform ceases immediately. We may retain certain data as
      required by law or for legitimate business purposes.
    </p>

    <h3 className="text-base font-semibold text-foreground mt-6">10. Changes to Terms</h3>
    <p>
      We reserve the right to modify these Terms at any time. Material changes will be communicated via email or
      in-app notification. Continued use of the Platform after changes constitutes acceptance of the updated Terms.
    </p>

    <h3 className="text-base font-semibold text-foreground mt-6">11. Contact</h3>
    <p>
      For questions about these Terms, please contact us at{" "}
      <a href="mailto:support@neeshai.com" className="text-primary hover:underline">support@neeshai.com</a>.
    </p>
  </div>
);

// ─── Privacy Policy Content ───
const PrivacyContent = () => (
  <div className="prose prose-sm dark:prose-invert max-w-none space-y-4 text-sm text-muted-foreground leading-relaxed">
    <p className="text-xs text-muted-foreground/70 italic">Last Updated: March 2026</p>

    <p>
      Your privacy is important to us at <strong className="text-foreground">Neesh AI</strong>. This Privacy Policy
      explains how we collect, use, store, and protect your personal information when you use our platform.
    </p>

    <h3 className="text-base font-semibold text-foreground mt-6">1. Information We Collect</h3>
    <p>We collect the following types of information:</p>
    <ul className="list-disc pl-5 space-y-1">
      <li><strong>Account Information:</strong> Name, email address, and profile image when you create an account</li>
      <li><strong>Authentication Data:</strong> Securely managed through Supabase Auth (email/password, Google, or GitHub OAuth)</li>
      <li><strong>Project Data:</strong> Ideas, blog content, audience personas, feedback responses, and chatbot interactions you create</li>
      <li><strong>Uploaded Documents:</strong> Files you upload to the knowledge base for AI processing</li>
      <li><strong>API Keys:</strong> Third-party AI provider keys you choose to store (encrypted at rest)</li>
      <li><strong>Usage Data:</strong> Feature usage patterns, session duration, and platform interactions</li>
    </ul>

    <h3 className="text-base font-semibold text-foreground mt-6">2. How We Use Your Information</h3>
    <ul className="list-disc pl-5 space-y-1">
      <li>To provide and improve our AI-powered validation services</li>
      <li>To generate personalized insights, blog posts, and audience analyses</li>
      <li>To process feedback forms and chatbot interactions</li>
      <li>To send service-related communications (account verification, OTPs, notifications)</li>
      <li>To detect and prevent fraud, abuse, and security threats</li>
      <li>To comply with legal obligations</li>
    </ul>

    <h3 className="text-base font-semibold text-foreground mt-6">3. Data Storage & Security</h3>
    <p>
      Your data is stored securely using Supabase (PostgreSQL) with enterprise-grade encryption. API keys are
      encrypted using AES-256 before storage. We use HTTPS for all data transmission and implement industry-standard
      security practices.
    </p>

    <h3 className="text-base font-semibold text-foreground mt-6">4. Third-Party Services</h3>
    <p>We integrate with the following third-party services:</p>
    <ul className="list-disc pl-5 space-y-1">
      <li><strong>Supabase:</strong> Authentication and database hosting</li>
      <li><strong>AI Providers (OpenAI, Claude, Gemini, OpenRouter):</strong> For content generation and analysis</li>
      <li><strong>Resend:</strong> For transactional emails (OTPs, notifications)</li>
      <li><strong>Google & GitHub OAuth:</strong> For social sign-in</li>
    </ul>
    <p>
      When you use third-party AI providers with your own API keys, your data is subject to their respective privacy
      policies.
    </p>

    <h3 className="text-base font-semibold text-foreground mt-6">5. Data Retention</h3>
    <p>
      We retain your data for as long as your account is active. Upon account deletion, we will delete your personal
      data within 30 days, except where retention is required by law. Anonymized, aggregated data may be retained for
      analytics purposes.
    </p>

    <h3 className="text-base font-semibold text-foreground mt-6">6. Your Rights</h3>
    <p>You have the right to:</p>
    <ul className="list-disc pl-5 space-y-1">
      <li>Access your personal data stored on the Platform</li>
      <li>Request correction of inaccurate data</li>
      <li>Request deletion of your data and account</li>
      <li>Export your project data</li>
      <li>Withdraw consent for data processing</li>
    </ul>

    <h3 className="text-base font-semibold text-foreground mt-6">7. Cookies</h3>
    <p>
      We use essential cookies for authentication and session management. We do not use third-party advertising or
      tracking cookies.
    </p>

    <h3 className="text-base font-semibold text-foreground mt-6">8. Children's Privacy</h3>
    <p>
      Neesh AI is not intended for users under 18 years of age. We do not knowingly collect personal information from
      minors.
    </p>

    <h3 className="text-base font-semibold text-foreground mt-6">9. Changes to This Policy</h3>
    <p>
      We may update this Privacy Policy from time to time. We will notify you of significant changes via email or
      in-app notification.
    </p>

    <h3 className="text-base font-semibold text-foreground mt-6">10. Contact Us</h3>
    <p>
      For privacy-related inquiries, contact us at{" "}
      <a href="mailto:privacy@neeshai.com" className="text-primary hover:underline">privacy@neeshai.com</a>.
    </p>
  </div>
);

export default TermsAndConditions;
